---
# ====== Application: HarborManager ==========================
identification: 
  name: HarborManager
  alias: HARBORMANAGER
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: insum_error_handler_api.error_handler

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 104632684517525427

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application
  - Modify Workspace Repository

database-session: 
  parsing-schema: WKSP_WS155963

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: 'DD-MM-YYYY HH24:MI:SS'
  timestamp-time-zone: 'DD-MM-YYYY HH24:MI:SS'

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Harbor Manager

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Main

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 104633493000525431

navigation-bar: 
  implementation: List
  list: Navigation Bar # 104922831460525810
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Harbormanager

component-settings: 
- # ====== Component Setting: NATIVE_IR ========================
  id: 104628422836525423
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 104628775834525423
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 104629027717525423
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 104629312722525423
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 104629642230525424
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 104629961581525424
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 104630226878525424
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 104630556452525424
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 104630847917525425
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 104631133538525425
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 104631447970525425
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 104631765500525426
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 430338166

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 104632091158525426
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 430338166

